
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun May 20 17:59:52 CDT 2018
//----------------------------------------------------

package mx.com.mont.murcielago.grammar;

import mx.com.mont.murcielago.lexer.LexerF;
import java_cup.runtime.*;
import java.io.*;

/** CUP v0.10k generated parser.
  * @version Sun May 20 17:59:52 CDT 2018
  */
public class parser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\045\000\002\002\004\000\002\003\013\000\002\003" +
    "\012\000\002\005\006\000\002\005\006\000\002\005\004" +
    "\000\002\005\004\000\002\006\003\000\002\006\003\000" +
    "\002\006\003\000\002\006\003\000\002\006\003\000\002" +
    "\006\003\000\002\006\003\000\002\006\003\000\002\006" +
    "\003\000\002\006\003\000\002\004\006\000\002\004\007" +
    "\000\002\004\006\000\002\004\005\000\002\004\014\000" +
    "\002\004\013\000\002\011\006\000\002\011\003\000\002" +
    "\012\003\000\002\012\005\000\002\012\007\000\002\010" +
    "\003\000\002\010\005\000\002\007\003\000\002\007\003" +
    "\000\002\007\003\000\002\007\003\000\002\013\003\000" +
    "\002\013\003\000\002\013\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\111\000\004\020\004\001\002\000\004\021\007\001" +
    "\002\000\004\002\006\001\002\000\004\002\001\001\002" +
    "\000\004\040\010\001\002\000\004\005\011\001\002\000" +
    "\006\004\012\022\014\001\002\000\004\006\111\001\002" +
    "\000\004\004\035\001\002\000\030\023\024\024\020\025" +
    "\022\026\015\027\026\030\030\031\025\032\016\033\027" +
    "\034\023\040\017\001\002\000\020\004\ufff7\010\ufff7\011" +
    "\ufff7\014\ufff7\015\ufff7\016\ufff7\017\ufff7\001\002\000\020" +
    "\004\ufff3\010\ufff3\011\ufff3\014\ufff3\015\ufff3\016\ufff3\017" +
    "\ufff3\001\002\000\006\004\ufffb\010\033\001\002\000\020" +
    "\004\ufff9\010\ufff9\011\ufff9\014\ufff9\015\ufff9\016\ufff9\017" +
    "\ufff9\001\002\000\006\004\ufffc\010\031\001\002\000\020" +
    "\004\ufff8\010\ufff8\011\ufff8\014\ufff8\015\ufff8\016\ufff8\017" +
    "\ufff8\001\002\000\020\004\ufff1\010\ufff1\011\ufff1\014\ufff1" +
    "\015\ufff1\016\ufff1\017\ufff1\001\002\000\020\004\ufffa\010" +
    "\ufffa\011\ufffa\014\ufffa\015\ufffa\016\ufffa\017\ufffa\001\002" +
    "\000\020\004\ufff4\010\ufff4\011\ufff4\014\ufff4\015\ufff4\016" +
    "\ufff4\017\ufff4\001\002\000\020\004\ufff6\010\ufff6\011\ufff6" +
    "\014\ufff6\015\ufff6\016\ufff6\017\ufff6\001\002\000\020\004" +
    "\ufff2\010\ufff2\011\ufff2\014\ufff2\015\ufff2\016\ufff2\017\ufff2" +
    "\001\002\000\020\004\ufff5\010\ufff5\011\ufff5\014\ufff5\015" +
    "\ufff5\016\ufff5\017\ufff5\001\002\000\004\022\014\001\002" +
    "\000\004\004\ufffd\001\002\000\004\022\014\001\002\000" +
    "\004\004\ufffe\001\002\000\004\006\036\001\002\000\010" +
    "\022\042\035\041\040\040\001\002\000\004\007\110\001" +
    "\002\000\004\013\062\001\002\000\004\012\051\001\002" +
    "\000\032\023\024\024\020\025\022\026\015\027\026\030" +
    "\030\031\025\032\016\033\027\034\023\040\044\041\043" +
    "\001\002\000\016\004\uffde\011\uffde\014\uffde\015\uffde\016" +
    "\uffde\017\uffde\001\002\000\016\004\uffdd\011\uffdd\014\uffdd" +
    "\015\uffdd\016\uffdd\017\uffdd\001\002\000\016\004\uffdf\011" +
    "\uffdf\014\uffdf\015\uffdf\016\uffdf\017\uffdf\001\002\000\004" +
    "\011\047\001\002\000\012\007\uffed\022\042\035\041\040" +
    "\040\001\002\000\004\007\uffee\001\002\000\004\036\052" +
    "\001\002\000\004\012\053\001\002\000\004\037\054\001" +
    "\002\000\004\005\055\001\002\000\032\023\024\024\020" +
    "\025\022\026\015\027\026\030\030\031\025\032\016\033" +
    "\027\034\023\040\044\041\043\001\002\000\004\004\057" +
    "\001\002\000\004\011\060\001\002\000\012\007\uffeb\022" +
    "\042\035\041\040\040\001\002\000\004\007\uffec\001\002" +
    "\000\034\005\066\023\024\024\020\025\022\026\015\027" +
    "\026\030\030\031\025\032\016\033\027\034\023\040\044" +
    "\041\043\001\002\000\004\011\106\001\002\000\004\011" +
    "\uffe9\001\002\000\016\004\uffe5\011\uffe5\014\102\015\101" +
    "\016\077\017\100\001\002\000\034\022\071\023\024\024" +
    "\020\025\022\026\015\027\026\030\030\031\025\032\016" +
    "\033\027\034\023\040\044\041\043\001\002\000\004\011" +
    "\uffe8\001\002\000\004\004\075\001\002\000\004\004\072" +
    "\001\002\000\034\005\074\023\024\024\020\025\022\026" +
    "\015\027\026\030\030\031\025\032\016\033\027\034\023" +
    "\040\044\041\043\001\002\000\004\011\uffea\001\002\000" +
    "\032\023\024\024\020\025\022\026\015\027\026\030\030" +
    "\031\025\032\016\033\027\034\023\040\044\041\043\001" +
    "\002\000\014\011\uffe7\014\102\015\101\016\077\017\100" +
    "\001\002\000\034\005\074\023\024\024\020\025\022\026" +
    "\015\027\026\030\030\031\025\032\016\033\027\034\023" +
    "\040\044\041\043\001\002\000\034\005\uffe2\023\uffe2\024" +
    "\uffe2\025\uffe2\026\uffe2\027\uffe2\030\uffe2\031\uffe2\032\uffe2" +
    "\033\uffe2\034\uffe2\040\uffe2\041\uffe2\001\002\000\034\005" +
    "\uffe0\023\uffe0\024\uffe0\025\uffe0\026\uffe0\027\uffe0\030\uffe0" +
    "\031\uffe0\032\uffe0\033\uffe0\034\uffe0\040\uffe0\041\uffe0\001" +
    "\002\000\034\005\uffe3\023\uffe3\024\uffe3\025\uffe3\026\uffe3" +
    "\027\uffe3\030\uffe3\031\uffe3\032\uffe3\033\uffe3\034\uffe3\040" +
    "\uffe3\041\uffe3\001\002\000\034\005\uffe1\023\uffe1\024\uffe1" +
    "\025\uffe1\026\uffe1\027\uffe1\030\uffe1\031\uffe1\032\uffe1\033" +
    "\uffe1\034\uffe1\040\uffe1\041\uffe1\001\002\000\004\011\uffe6" +
    "\001\002\000\032\023\024\024\020\025\022\026\015\027" +
    "\026\030\030\031\025\032\016\033\027\034\023\040\044" +
    "\041\043\001\002\000\006\004\uffe4\011\uffe4\001\002\000" +
    "\012\007\ufff0\022\042\035\041\040\040\001\002\000\004" +
    "\007\uffef\001\002\000\004\002\000\001\002\000\010\022" +
    "\042\035\041\040\040\001\002\000\004\007\113\001\002" +
    "\000\004\002\uffff\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\111\000\004\003\004\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\005\012\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\006\020\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\005\031\001\001\000\002" +
    "\001\001\000\004\005\033\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\004\036\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\006\006\044\013" +
    "\045\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\004\047\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\006\006\044\013\055\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\004\060" +
    "\001\001\000\002\001\001\000\014\006\044\010\066\011" +
    "\062\012\063\013\064\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\007\103\001\001\000\010\006\044\010" +
    "\067\013\064\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\012\006\044\010\066\012\072\013" +
    "\064\001\001\000\002\001\001\000\010\006\044\010\067" +
    "\013\064\001\001\000\004\007\075\001\001\000\012\006" +
    "\044\010\066\012\102\013\064\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\010\006\044\010\104\013\064\001\001" +
    "\000\002\001\001\000\004\004\106\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\004\111\001\001\000\002" +
    "\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



	 /* Change the method report_error so it will display the line and
       column of where the error occurred in the input as well as the
       reason for the error which is passed into the method in the
       String 'message'. */
	private javax.swing.JTextPane console;
	private boolean hasError;
	public void setError(boolean e){ this.hasError=e;}
	public boolean hasError(){ return this.hasError; }
	public void setConsole(javax.swing.JTextPane comp){
		this.console=comp;
	}
    public void report_error(String message, Object info) {
   
        /* Create a StringBuilder called 'm' with the string 'Error' in it. */
        StringBuilder m = new StringBuilder("Error");
   
        /* Check if the information passed to the method is the same
           type as the type java_cup.runtime.Symbol. */
        if (info instanceof java_cup.runtime.Symbol) {
            /* Declare a java_cup.runtime.Symbol object 's' with the
               information in the object info that is being typecasted
               as a java_cup.runtime.Symbol object. */
            java_cup.runtime.Symbol s = ((java_cup.runtime.Symbol) info);
   
            /* Check if the line number in the input is greater or
               equal to zero. */
            if (s.left >= 0) {                
                /* Add to the end of the StringBuilder error message
                   the line number of the error in the input. */
                m.append(" in line "+(s.left+1));   
                /* Check if the column number in the input is greater
                   or equal to zero. */
                if (s.right >= 0)                    
                    /* Add to the end of the StringBuilder error message
                       the column number of the error in the input. */
                    m.append(", column "+(s.right));
            }
        }
   
        /* Add to the end of the StringBuilder error message created in
           this method the message that was passed into this method. */
        m.append(" : "+message);
		m.append(" Illegal caracter < "+((LexerF)super.getScanner()).yytext()+" >");
        console.setText(m.toString());
		hasError=true;
        //System.err.println(m); // if we want to see errors in console 
    }

    public void report_fatal_error(String message, Object info) throws Exception {
        report_error(message, info);
    }

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$parser$actions {
  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // dato ::= IDE 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(9/*dato*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // dato ::= NUMI 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(9/*dato*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // dato ::= murcielago 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(9/*dato*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // operador ::= MULT 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(5/*operador*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // operador ::= DIVI 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(5/*operador*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // operador ::= RESTA 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(5/*operador*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // operador ::= SUMA 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(5/*operador*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // operacion ::= dato operador operacion 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(6/*operacion*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // operacion ::= dato 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(6/*operacion*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // asignar ::= PAR_IZQ operacion PAR_DER operador asignar 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(8/*asignar*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // asignar ::= PAR_IZQ operacion PAR_DER 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(8/*asignar*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // asignar ::= operacion 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(8/*asignar*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // asignacion ::= asignar 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(7/*asignacion*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // asignacion ::= PAR_IZQ FLOAT PAR_DER asignar 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(7/*asignacion*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // body ::= SYSTEM PUNTO OUT PUNTO PRINTLN PAR_IZQ dato PAR_DER SEMICOLON 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(2/*body*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // body ::= SYSTEM PUNTO OUT PUNTO PRINTLN PAR_IZQ dato PAR_DER SEMICOLON body 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(2/*body*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-9)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // body ::= FLOAT dato SEMICOLON 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(2/*body*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // body ::= FLOAT dato SEMICOLON body 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(2/*body*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // body ::= IDE ASIGNACION asignacion SEMICOLON body 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(2/*body*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // body ::= IDE ASIGNACION asignacion SEMICOLON 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(2/*body*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // murcielago ::= O 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(4/*murcielago*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // murcielago ::= G 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(4/*murcielago*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // murcielago ::= A 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(4/*murcielago*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // murcielago ::= L 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(4/*murcielago*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // murcielago ::= E 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(4/*murcielago*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // murcielago ::= I 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(4/*murcielago*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // murcielago ::= C 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(4/*murcielago*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // murcielago ::= R 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(4/*murcielago*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // murcielago ::= U 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(4/*murcielago*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // murcielago ::= M 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(4/*murcielago*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // param ::= FLOAT IDE 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(3/*param*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // param ::= FLOAT murcielago 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(3/*param*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // param ::= FLOAT murcielago COMA param 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(3/*param*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // param ::= FLOAT IDE COMA param 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(3/*param*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // inicio ::= PUBLIC VOID IDE PAR_IZQ PAR_DER LL_IZQ body LL_DER 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(1/*inicio*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // inicio ::= PUBLIC VOID IDE PAR_IZQ param PAR_DER LL_IZQ body LL_DER 
            {
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(1/*inicio*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= inicio EOF 
            {
              Object RESULT = null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = new java_cup.runtime.Symbol(0/*$START*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

