
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue May 15 20:58:33 CDT 2018
//----------------------------------------------------

package mx.com.mont.murcielago.grammar;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int IDE = 27;
  public static final int PUNTO = 8;
  public static final int SEMICOLON = 7;
  public static final int U = 18;
  public static final int SUMA = 11;
  public static final int DIVI = 10;
  public static final int R = 19;
  public static final int NUMI = 28;
  public static final int O = 26;
  public static final int M = 17;
  public static final int L = 23;
  public static final int PUBLIC = 14;
  public static final int I = 21;
  public static final int G = 25;
  public static final int LL_IZQ = 4;
  public static final int COMA = 6;
  public static final int E = 22;
  public static final int ASIGNACION = 9;
  public static final int FLOAT = 16;
  public static final int LL_DER = 5;
  public static final int C = 20;
  public static final int EOF = 0;
  public static final int MULT = 13;
  public static final int A = 24;
  public static final int PAR_IZQ = 3;
  public static final int error = 1;
  public static final int PAR_DER = 2;
  public static final int VOID = 15;
  public static final int RESTA = 12;
}

